<?PHP


$l1='Con fundamento en lo dispuesto por';
$l2='los artículos 4, 7, 8, 10, 11, 13, 15 y';
$l3='demás relativos del Reglamento';
$l4='aplicable a los  Comités Voluntarios';
$l5='de Promoción y Defensa de los Derechos Humanos aprobado en sesión ordinaria del Honorable Consejo';
$l6='de la Comisión de Derechos Humanos del Estado de Colima el  17 de Mayo de 2010 y cumpliendo con';
$l7='los requisitos previstos en el ordenamiento anteriormente citado, la Comisión Estatal por conducto';
$l8='del Presidente, LIC. ROBERTO CHAPULA DE LA MORA otorga a:';


ECHO  "<br>".strlen($l1);
ECHO  "<br>".strlen($l2);
ECHO  "<br>".strlen($l3);
ECHO  "<br>".strlen($l4);
ECHO  "<br>".strlen($l5);
ECHO  "<br>".strlen($l6);
ECHO  "<br>".strlen($l7);
ECHO  "<br>".strlen($l8);


?>